porch_brightness:
  name: Front Porch Brightness
  min: 0
  max: 255
  initial: 255
  step: 1

living_room_lamp_brightness:
  name: Lamp Brightness
  min: 0
  max: 255
  initial: 255
  step: 1

kitchen_brightness:
  name: Kitchen Brightness
  min: 0
  max: 255
  initial: 255
  step: 1

kids_room_brightness:
  name: Kids Brightness
  min: 0
  max: 255
  initial: 255
  step: 1

parents_room_brightness:
  name: Parents Room Brightness
  min: 0
  max: 255
  initial: 255
  step: 1

parents_lamp_red:
  name: Lamp Red
  min: 0
  max: 255
  initial: 255
  step: 1

parents_lamp_green:
  name: Lamp Green
  min: 0
  max: 255
  initial: 255
  step: 1

parents_lamp_blue:
  name: Lamp Blue
  min: 0
  max: 255
  initial: 255
  step: 1

basement_living_room_lamp_brightness:
  name: Basement Lamp Brightness
  min: 0
  max: 255
  initial: 255
  step: 1

pb_candle_1_red:
  name: Playbulb Candle 1 Red
  min: 0
  max: 255
  initial: 255
  step: 1

pb_candle_1_green:
  name: Playbulb Candle 1 Green
  min: 0
  max: 255
  initial: 255
  step: 1

pb_candle_1_blue:
  name: Playbulb Candle 1 Blue
  min: 0
  max: 255
  initial: 255
  step: 1

# Parents Room TV
parents_tv_volume:
  name: Volume
  min: 0
  max: 25
  initial: 8
  step: 1
